//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientJourney.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand_Master
    {
        public Brand_Master()
        {
            this.Favourite_Search_Brand = new HashSet<Favourite_Search_Brand>();
            this.Journey_Pdf = new HashSet<Journey_Pdf>();
            this.Patient_Journey_Temp = new HashSet<Patient_Journey_Temp>();
            this.Patient_Journey = new HashSet<Patient_Journey>();
        }
    
        public int Brand_Master_Id { get; set; }
        public string Brand_Name { get; set; }
        public Nullable<int> Therapeutic_Area_Master_Id { get; set; }
        public Nullable<int> SubTherapeutic_Area_Master_Id { get; set; }
        public Nullable<int> Indication_Master_Id { get; set; }
        public bool Is_Active { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Indication_Master Indication_Master { get; set; }
        public virtual SubTherapeutic_Area_Master SubTherapeutic_Area_Master { get; set; }
        public virtual Therapeutic_Area_Master Therapeutic_Area_Master { get; set; }
        public virtual ICollection<Favourite_Search_Brand> Favourite_Search_Brand { get; set; }
        public virtual ICollection<Journey_Pdf> Journey_Pdf { get; set; }
        public virtual ICollection<Patient_Journey_Temp> Patient_Journey_Temp { get; set; }
        public virtual ICollection<Patient_Journey> Patient_Journey { get; set; }
    }
}
