//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientJourney.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image_Master
    {
        public Image_Master()
        {
            this.Clinical_Intervention_Master = new HashSet<Clinical_Intervention_Master>();
            this.Transaction_Location_Master = new HashSet<Transaction_Location_Master>();
            this.Transaction_Master = new HashSet<Transaction_Master>();
            this.SubClinical_Intervention_Master = new HashSet<SubClinical_Intervention_Master>();
        }
    
        public int Image_Master_Id { get; set; }
        public string Image_Name { get; set; }
        public string Image_Path { get; set; }
        public string Image_Description { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual ICollection<Clinical_Intervention_Master> Clinical_Intervention_Master { get; set; }
        public virtual ICollection<Transaction_Location_Master> Transaction_Location_Master { get; set; }
        public virtual ICollection<Transaction_Master> Transaction_Master { get; set; }
        public virtual ICollection<SubClinical_Intervention_Master> SubClinical_Intervention_Master { get; set; }
    }
}
