//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientJourney.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journey_Pdf
    {
        public int Id { get; set; }
        public int Brand_Id { get; set; }
        public int Country_Id { get; set; }
        public int Year { get; set; }
        public byte[] Pdf_Byte { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Brand_Master Brand_Master { get; set; }
        public virtual Country_Master Country_Master { get; set; }
        public virtual Year_Master Year_Master { get; set; }
    }
}
