//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientJourney.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Journey_Transactions
    {
        public Patient_Journey_Transactions()
        {
            this.Patient_Journey_Strategic_Moment = new HashSet<Patient_Journey_Strategic_Moment>();
            this.Patient_Journey_Strategic_Moment1 = new HashSet<Patient_Journey_Strategic_Moment>();
            this.Patient_Journey_Transactions_AssociatedCosts = new HashSet<Patient_Journey_Transactions_AssociatedCosts>();
            this.Patient_Journey_Transactions_DesiredOutcomes = new HashSet<Patient_Journey_Transactions_DesiredOutcomes>();
            this.Patient_Journey_HCP_Insights = new HashSet<Patient_Journey_HCP_Insights>();
            this.Patient_Journey_Patient_Insights = new HashSet<Patient_Journey_Patient_Insights>();
            this.Patient_Journey_Payor_Insights = new HashSet<Patient_Journey_Payor_Insights>();
        }
    
        public int Patient_Journey_Transactions_Id { get; set; }
        public string Transaction_Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Patient_Journey_Id { get; set; }
        public Nullable<int> Patient_Journey_Stages_Id { get; set; }
        public Nullable<int> Transaction_Master_Id { get; set; }
        public Nullable<int> Transaction_Location_Master_Id { get; set; }
        public Nullable<int> Transaction_Display_Order { get; set; }
        public string Transaction_Location_Title { get; set; }
        public int HCP_Rating { get; set; }
        public int Payer_Rating { get; set; }
        public int Patient_Rating { get; set; }
        public int Feasibility_Rating { get; set; }
        public int Viability_Rating { get; set; }
        public string HCP_Description { get; set; }
        public string Payer_Description { get; set; }
        public string Patient_Description { get; set; }
        public string Feasibility_Description { get; set; }
        public string Viability_Description { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Patient_Evidence { get; set; }
        public string HCP_Evidence { get; set; }
        public string Payer_Evidence { get; set; }
        public string Feasibility_Evidence { get; set; }
        public string Viability_Evidence { get; set; }
        public Nullable<int> Patient_Journey_Transactions_Temp_Id { get; set; }
    
        public virtual ICollection<Patient_Journey_Strategic_Moment> Patient_Journey_Strategic_Moment { get; set; }
        public virtual ICollection<Patient_Journey_Strategic_Moment> Patient_Journey_Strategic_Moment1 { get; set; }
        public virtual ICollection<Patient_Journey_Transactions_AssociatedCosts> Patient_Journey_Transactions_AssociatedCosts { get; set; }
        public virtual ICollection<Patient_Journey_Transactions_DesiredOutcomes> Patient_Journey_Transactions_DesiredOutcomes { get; set; }
        public virtual Transaction_Master Transaction_Master { get; set; }
        public virtual Transaction_Location_Master Transaction_Location_Master { get; set; }
        public virtual ICollection<Patient_Journey_HCP_Insights> Patient_Journey_HCP_Insights { get; set; }
        public virtual ICollection<Patient_Journey_Patient_Insights> Patient_Journey_Patient_Insights { get; set; }
        public virtual ICollection<Patient_Journey_Payor_Insights> Patient_Journey_Payor_Insights { get; set; }
    }
}
