//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientJourney.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Journey_Temp
    {
        public Patient_Journey_Temp()
        {
            this.Patient_Journey_Stages_Temp = new HashSet<Patient_Journey_Stages_Temp>();
            this.Patient_Journey_Strategic_Moment_Temp = new HashSet<Patient_Journey_Strategic_Moment_Temp>();
            this.Patient_Journey_Transactions_Temp = new HashSet<Patient_Journey_Transactions_Temp>();
            this.Patient_Journey_VersionDetails_Temp = new HashSet<Patient_Journey_VersionDetails_Temp>();
            this.Patient_Journey_HCP_Insights_Temp = new HashSet<Patient_Journey_HCP_Insights_Temp>();
            this.Patient_Journey_Patient_Insights_Temp = new HashSet<Patient_Journey_Patient_Insights_Temp>();
            this.Patient_Journey_Payor_Insights_Temp = new HashSet<Patient_Journey_Payor_Insights_Temp>();
        }
    
        public int Patient_Journey_Temp_Id { get; set; }
        public string Journey_Title { get; set; }
        public int Patient_Journey_Id { get; set; }
        public int Brand_Master_Id { get; set; }
        public int Country_Master_Id { get; set; }
        public int Status_Master_Id { get; set; }
        public string User_Comments { get; set; }
        public string Approver_Comments { get; set; }
        public int Year { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Submitted_By { get; set; }
        public Nullable<System.DateTime> Submitted_Date { get; set; }
        public string Approved_By { get; set; }
        public Nullable<System.DateTime> Approved_Date { get; set; }
        public string Journey_Description { get; set; }
    
        public virtual Brand_Master Brand_Master { get; set; }
        public virtual Country_Master Country_Master { get; set; }
        public virtual Patient_Journey Patient_Journey { get; set; }
        public virtual ICollection<Patient_Journey_Stages_Temp> Patient_Journey_Stages_Temp { get; set; }
        public virtual ICollection<Patient_Journey_Strategic_Moment_Temp> Patient_Journey_Strategic_Moment_Temp { get; set; }
        public virtual ICollection<Patient_Journey_Transactions_Temp> Patient_Journey_Transactions_Temp { get; set; }
        public virtual Status_Master Status_Master { get; set; }
        public virtual ICollection<Patient_Journey_VersionDetails_Temp> Patient_Journey_VersionDetails_Temp { get; set; }
        public virtual ICollection<Patient_Journey_HCP_Insights_Temp> Patient_Journey_HCP_Insights_Temp { get; set; }
        public virtual ICollection<Patient_Journey_Patient_Insights_Temp> Patient_Journey_Patient_Insights_Temp { get; set; }
        public virtual ICollection<Patient_Journey_Payor_Insights_Temp> Patient_Journey_Payor_Insights_Temp { get; set; }
    }
}
