//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientJourney.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Journey_Strategic_Moment
    {
        public int Patient_Journey_Strategic_Moment_Id { get; set; }
        public Nullable<int> Patient_Journey_Start_Stage_Id { get; set; }
        public Nullable<int> Patient_Journey_End_Stage_Id { get; set; }
        public Nullable<int> Patient_Journey_Start_Transaction_Id { get; set; }
        public Nullable<int> Patient_Journey_End_Transaction_Id { get; set; }
        public string Description { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Patient_Journey_Id { get; set; }
        public string Category { get; set; }
        public Nullable<int> Patient_Journey_Strategic_Moment_Temp_Id { get; set; }
        public string Title { get; set; }
    
        public virtual Patient_Journey Patient_Journey { get; set; }
        public virtual Patient_Journey_Stages Patient_Journey_Stages { get; set; }
        public virtual Patient_Journey_Stages Patient_Journey_Stages1 { get; set; }
        public virtual Patient_Journey_Strategic_Moment_Temp Patient_Journey_Strategic_Moment_Temp { get; set; }
        public virtual Patient_Journey_Transactions Patient_Journey_Transactions { get; set; }
        public virtual Patient_Journey_Transactions Patient_Journey_Transactions1 { get; set; }
    }
}
