//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientJourney.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Journey_HCP_Insights
    {
        public int Patient_Journey_HCP_Insights_Id { get; set; }
        public int Patient_Journey_Id { get; set; }
        public int Patient_Journey_Transactions_Id { get; set; }
        public Nullable<int> Patient_Journey_Transactions_Temp_Id { get; set; }
        public string HCP_Insights { get; set; }
        public string Evidence { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Patient_Journey Patient_Journey { get; set; }
        public virtual Patient_Journey_Transactions Patient_Journey_Transactions { get; set; }
    }
}
