//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientJourney.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Journey_Payor_Insights_Temp
    {
        public int Patient_Journey_Payor_Insights_Temp_Id { get; set; }
        public int Patient_Journey_Temp_Id { get; set; }
        public int Patient_Journey_Transactions_Temp_Id { get; set; }
        public string Payor_Insights { get; set; }
        public string Evidence { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Patient_Journey_Temp Patient_Journey_Temp { get; set; }
        public virtual Patient_Journey_Transactions_Temp Patient_Journey_Transactions_Temp { get; set; }
    }
}
