//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientJourney.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Journey_Trans_Clin_Interventions
    {
        public Patient_Journey_Trans_Clin_Interventions()
        {
            this.Patient_Journey_Trans_SubClin_Interventions = new HashSet<Patient_Journey_Trans_SubClin_Interventions>();
        }
    
        public int Patient_Journey_Trans_Clin_Interventions_Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> Clinical_Intervention_Master_Id { get; set; }
        public Nullable<int> Patient_Journey_Transactions_Id { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Evidence { get; set; }
    
        public virtual Clinical_Intervention_Master Clinical_Intervention_Master { get; set; }
        public virtual ICollection<Patient_Journey_Trans_SubClin_Interventions> Patient_Journey_Trans_SubClin_Interventions { get; set; }
    }
}
