//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientJourney.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Journey_Stages
    {
        public Patient_Journey_Stages()
        {
            this.Patient_Journey_Strategic_Moment = new HashSet<Patient_Journey_Strategic_Moment>();
            this.Patient_Journey_Strategic_Moment1 = new HashSet<Patient_Journey_Strategic_Moment>();
        }
    
        public int Patient_Journey_Stages_Id { get; set; }
        public Nullable<int> Patient_Journey_Id { get; set; }
        public Nullable<int> Stage_Master_Id { get; set; }
        public string Stage_Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Stage_Display_Order { get; set; }
        public int Population_Statistics { get; set; }
        public int Time_Statistics { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Patient_Journey_Stages_Temp_Id { get; set; }
    
        public virtual Patient_Journey Patient_Journey { get; set; }
        public virtual ICollection<Patient_Journey_Strategic_Moment> Patient_Journey_Strategic_Moment { get; set; }
        public virtual ICollection<Patient_Journey_Strategic_Moment> Patient_Journey_Strategic_Moment1 { get; set; }
        public virtual Stage_Master Stage_Master { get; set; }
    }
}
