//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientJourney.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Journey_Transactions_DesiredOutcomes_Temp
    {
        public int Patient_Journey_Transactions_DesiredOutcomes_Temp_Id { get; set; }
        public string DesiredOutcomes { get; set; }
        public string Description { get; set; }
        public int Patient_Journey_Transactions_Temp_Id { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string MODIFIED_By { get; set; }
        public Nullable<System.DateTime> MODIFIED_Date { get; set; }
        public string Evidence { get; set; }
    
        public virtual Patient_Journey_Transactions_Temp Patient_Journey_Transactions_Temp { get; set; }
    }
}
