//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientJourney.DataAccess.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PJEntities : DbContext
    {
        public PJEntities()
            : base("name=PJEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Archetype_Master> Archetype_Master { get; set; }
        public DbSet<Area_Master> Area_Master { get; set; }
        public DbSet<Brand_Master> Brand_Master { get; set; }
        public DbSet<Clinical_Intervention_Master> Clinical_Intervention_Master { get; set; }
        public DbSet<Country_Master> Country_Master { get; set; }
        public DbSet<Favourite_Search> Favourite_Search { get; set; }
        public DbSet<Favourite_Search_Archetype> Favourite_Search_Archetype { get; set; }
        public DbSet<Favourite_Search_Area> Favourite_Search_Area { get; set; }
        public DbSet<Favourite_Search_Brand> Favourite_Search_Brand { get; set; }
        public DbSet<Favourite_Search_Country> Favourite_Search_Country { get; set; }
        public DbSet<Image_Master> Image_Master { get; set; }
        public DbSet<Indication_Master> Indication_Master { get; set; }
        public DbSet<Role_Master> Role_Master { get; set; }
        public DbSet<Stage_Master> Stage_Master { get; set; }
        public DbSet<Status_Master> Status_Master { get; set; }
        public DbSet<SubTherapeutic_Area_Master> SubTherapeutic_Area_Master { get; set; }
        public DbSet<Therapeutic_Area_Master> Therapeutic_Area_Master { get; set; }
        public DbSet<Transaction_Location_Master> Transaction_Location_Master { get; set; }
        public DbSet<Transaction_Master> Transaction_Master { get; set; }
        public DbSet<User_Country_Association> User_Country_Association { get; set; }
        public DbSet<User_Logon_Audit> User_Logon_Audit { get; set; }
        public DbSet<User_Logon_Audit_MS> User_Logon_Audit_MS { get; set; }
        public DbSet<User_Roles> User_Roles { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<SubClinical_Intervention_Master> SubClinical_Intervention_Master { get; set; }
        public DbSet<Journey_Pdf> Journey_Pdf { get; set; }
        public DbSet<Year_Master> Year_Master { get; set; }
        public DbSet<Journey_Pdf_TempData> Journey_Pdf_TempData { get; set; }
        public DbSet<Patient_Journey> Patient_Journey { get; set; }
        public DbSet<Patient_Journey_Stages> Patient_Journey_Stages { get; set; }
        public DbSet<Patient_Journey_Stages_Temp> Patient_Journey_Stages_Temp { get; set; }
        public DbSet<Patient_Journey_Strategic_Moment> Patient_Journey_Strategic_Moment { get; set; }
        public DbSet<Patient_Journey_Strategic_Moment_Temp> Patient_Journey_Strategic_Moment_Temp { get; set; }
        public DbSet<Patient_Journey_Temp> Patient_Journey_Temp { get; set; }
        public DbSet<Patient_Journey_Trans_Clin_Interventions> Patient_Journey_Trans_Clin_Interventions { get; set; }
        public DbSet<Patient_Journey_Trans_Clin_Interventions_Temp> Patient_Journey_Trans_Clin_Interventions_Temp { get; set; }
        public DbSet<Patient_Journey_Trans_SubClin_Interventions> Patient_Journey_Trans_SubClin_Interventions { get; set; }
        public DbSet<Patient_Journey_Trans_SubClin_Interventions_Temp> Patient_Journey_Trans_SubClin_Interventions_Temp { get; set; }
        public DbSet<Patient_Journey_Transactions> Patient_Journey_Transactions { get; set; }
        public DbSet<Patient_Journey_Transactions_AssociatedCosts> Patient_Journey_Transactions_AssociatedCosts { get; set; }
        public DbSet<Patient_Journey_Transactions_AssociatedCosts_Temp> Patient_Journey_Transactions_AssociatedCosts_Temp { get; set; }
        public DbSet<Patient_Journey_Transactions_DesiredOutcomes> Patient_Journey_Transactions_DesiredOutcomes { get; set; }
        public DbSet<Patient_Journey_Transactions_DesiredOutcomes_Temp> Patient_Journey_Transactions_DesiredOutcomes_Temp { get; set; }
        public DbSet<Patient_Journey_Transactions_Temp> Patient_Journey_Transactions_Temp { get; set; }
        public DbSet<Patient_Journey_VersionDetails> Patient_Journey_VersionDetails { get; set; }
        public DbSet<Patient_Journey_VersionDetails_Temp> Patient_Journey_VersionDetails_Temp { get; set; }
        public DbSet<Patient_Journey_HCP_Insights> Patient_Journey_HCP_Insights { get; set; }
        public DbSet<Patient_Journey_HCP_Insights_Temp> Patient_Journey_HCP_Insights_Temp { get; set; }
        public DbSet<Patient_Journey_Patient_Insights> Patient_Journey_Patient_Insights { get; set; }
        public DbSet<Patient_Journey_Patient_Insights_Temp> Patient_Journey_Patient_Insights_Temp { get; set; }
        public DbSet<Patient_Journey_Payor_Insights> Patient_Journey_Payor_Insights { get; set; }
        public DbSet<Patient_Journey_Payor_Insights_Temp> Patient_Journey_Payor_Insights_Temp { get; set; }
    }
}
