//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientJourney.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage_Master
    {
        public Stage_Master()
        {
            this.Patient_Journey_Stages = new HashSet<Patient_Journey_Stages>();
            this.Patient_Journey_Stages_Temp = new HashSet<Patient_Journey_Stages_Temp>();
        }
    
        public int Stage_Master_Id { get; set; }
        public string Stage_Name { get; set; }
        public string Stage_Description { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual ICollection<Patient_Journey_Stages> Patient_Journey_Stages { get; set; }
        public virtual ICollection<Patient_Journey_Stages_Temp> Patient_Journey_Stages_Temp { get; set; }
    }
}
