//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientJourney.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_Master
    {
        public Status_Master()
        {
            this.Patient_Journey = new HashSet<Patient_Journey>();
            this.Patient_Journey_Temp = new HashSet<Patient_Journey_Temp>();
        }
    
        public int Status_Master_Id { get; set; }
        public string Status_Name { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual ICollection<Patient_Journey> Patient_Journey { get; set; }
        public virtual ICollection<Patient_Journey_Temp> Patient_Journey_Temp { get; set; }
    }
}
