//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientJourney.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Logon_Audit_MS
    {
        public int User_Logon_Audit_Id { get; set; }
        public string User_511 { get; set; }
        public string UPI { get; set; }
        public string First_Name { get; set; }
        public string Middle_Initial { get; set; }
        public string Last_Name { get; set; }
        public string Email_Id { get; set; }
        public Nullable<System.DateTimeOffset> Logon_Client_Date { get; set; }
        public Nullable<System.DateTimeOffset> Logon_UTC_Date { get; set; }
        public string Logon_Client_TimeZone { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTimeOffset> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTimeOffset> Modified_Date { get; set; }
    }
}
