//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientJourney.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Favourite_Search = new HashSet<Favourite_Search>();
            this.Favourite_Search_Archetype = new HashSet<Favourite_Search_Archetype>();
            this.Favourite_Search_Area = new HashSet<Favourite_Search_Area>();
            this.Favourite_Search_Brand = new HashSet<Favourite_Search_Brand>();
            this.Favourite_Search_Country = new HashSet<Favourite_Search_Country>();
            this.User_Country_Association = new HashSet<User_Country_Association>();
            this.User_Roles = new HashSet<User_Roles>();
        }
    
        public int User_Id { get; set; }
        public string User_511 { get; set; }
        public decimal UPI { get; set; }
        public string First_Name { get; set; }
        public string Middle_Initial { get; set; }
        public string Last_Name { get; set; }
        public string Email_Id { get; set; }
        public bool Is_Active { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual ICollection<Favourite_Search> Favourite_Search { get; set; }
        public virtual ICollection<Favourite_Search_Archetype> Favourite_Search_Archetype { get; set; }
        public virtual ICollection<Favourite_Search_Area> Favourite_Search_Area { get; set; }
        public virtual ICollection<Favourite_Search_Brand> Favourite_Search_Brand { get; set; }
        public virtual ICollection<Favourite_Search_Country> Favourite_Search_Country { get; set; }
        public virtual ICollection<User_Country_Association> User_Country_Association { get; set; }
        public virtual ICollection<User_Roles> User_Roles { get; set; }
    }
}
